"""Export workflow demo results as static JSON for GitHub Pages."""

import asyncio
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from genai_hub.workflows.engine import WorkflowEngine


async def main() -> None:
    engine = WorkflowEngine()
    email = (
        "Sehr geehrte Damen und Herren,\n"
        "bitte bestellen Sie 5 Stück SKU-A100 für Kunde CUST-4521.\n"
        "Bei Fragen: billing@mueller-ag.ch\n"
        "Freundliche Grüsse, Müller AG"
    )

    output = {
        "provider": "mock",
        "note": "Generated by scripts/export_demo_output.py — no API keys required.",
        "workflows": {
            "crm_ticket_triage": (await engine.crm_ticket_triage("TKT-1001")).model_dump(),
            "email_order_extraction": (await engine.email_order_extraction(email)).model_dump(),
            "document_summarization": (await engine.document_summarization("DOC-ROADMAP-Q2")).model_dump(),
        },
    }

    target = ROOT / "docs" / "demo-output.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(output, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {target}")


if __name__ == "__main__":
    asyncio.run(main())
